inherit_from: .rubocop_todo.yml

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%W': '[]'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 16

